name: Release on Github
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: ./.github/actions/yarn-nm-install

      - name: Build the Theatre.js packages
        run: yarn cli build
      
      - name: Pack core
        working-directory: ./theatre/core
        run: yarn pack --out core.tgz

      - name: Pack studio
        working-directory: ./theatre/studio
        run: yarn pack --out studio.tgz

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./theatre/core/core.tgz
            ./theatre/studio/studio.tgz
